name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  api:
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check Google Java Format
      run: mvn spotless:check
    - name: Build with Maven
      run: mvn -q package --file pom.xml -Dmaven.test.skip=true
    - name: Run tests
      run: mvn test
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: /api/target/site/jacoco/jacoco.xml